easy_admin:
    site_name: 'Bartech'
    entities:
        User:
          class: App\Entity\Admin\User
          form:
            fields:
                - username
                - email
                - enabled
                - lastLogin
