framework:
    templating: { engines: [twig] }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\Admin\User
    from_email: {address: "noreply@bartech.com", sender_name: Bartech}