<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWMbJ0Sl\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWMbJ0Sl/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWMbJ0Sl.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWMbJ0Sl\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerWMbJ0Sl\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'WMbJ0Sl',
    'container.build_id' => '0cc700c2',
    'container.build_time' => 1521112490,
));
